run:
  timeout: 5m
  go: "1.21"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gocritic
    - gofmt
    - goimports
    - gosec
    - misspell
    - unconvert
    - unparam
    - gocyclo
    - dupl
    - goconst
    - exportloopref

linters-settings:
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - dupl
